=== MilesStarr/TACTIC_ERP_Phase2BOM/BOM.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Parts">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Part" type="PartType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Group" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

  <xs:complexType name="PartType">
    <xs:sequence>
      <xs:element name="Operation" type="OperationType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="PartID" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="OperationType">
    <xs:sequence>
      <xs:element name="Material" type="MaterialType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="WC" type="xs:string" default="TACwip"/>
  </xs:complexType>

  <xs:complexType name="MaterialType">
    <xs:attribute name="PartID" type="xs:string" use="required"/>
    <xs:attribute name="Unit" type="xs:string" use="required"/>
    <xs:attribute name="Qty" type="xs:int" use="required"/>
    <xs:attribute name="Size" type="xs:float" use="optional"/>
  </xs:complexType>

  
</xs:schema>

=== MilesStarr/TACTIC_ERP_Phase2BOM/M265_266.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M265/M266"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">

	<Part PartID="8026865">
		<Operation WC="FAB010">
			<Material PartID="9070500-2" Unit="IN" Qty="1" Size="10.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>

	<Part PartID="8026870-1">
		<Operation WC="MCH010">
			<Material PartID="6331004" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026870-2">
		<Operation WC="MCH010">
			<Material PartID="6331004" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026868">
		<Operation WC="FAB010">
			<Material PartID="8025093" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026875">
		<Operation WC="MCH010">
			<Material PartID="6160005-2" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH070" />
		<Operation WC="ASY010">
			<Material PartID="6160005-3" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026871-1">
		<Operation WC="MCH010">
			<Material PartID="6160003" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026871-2">
		<Operation WC="MCH010">
			<Material PartID="6160003" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026869">
		<Operation WC="FAB010">
			<Material PartID="1402824" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />	
	</Part>
	
	<Part PartID="8026867">
		<Operation WC="FAB010">
			<Material PartID="9190060-1" Unit="IN" Qty="1" Size="2.000" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026864-B">
		<Operation WC="FAB010">
			<Material PartID="1402014" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8026864">
		<Operation WC="ASY010">
			<Material PartID="6372201" Unit="EA" Qty="1" />
			<Material PartID="8026864-B" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026873">
		<Operation WC="MCH060">
			<Material PartID="9191005" Unit="SF" Qty="1" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8026872">
		<Operation WC="MCH060">
			<Material PartID="9191005" Unit="SF" Qty="1" Size=".112" />
		</Operation>
	</Part>
	
	<Part PartID="8033662">
		<Operation WC="FAB010">
			<Material PartID="9070500-2" Unit="IN" Qty="1" Size="11.125" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8033663">
		<Operation WC="FAB010">
			<Material PartID="9070300-2" Unit="IN" Qty="1" Size="4.375" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8033664">
		<Operation WC="FAB010">
			<Material PartID="9070300-2" Unit="IN" Qty="1" Size="2.625" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8033769">
		<Operation WC="MCH010">
			<Material PartID="6372008" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="M265">
		<Operation WC="ASY010">
			<Material PartID="6331001" Unit="EA" Qty="1" />
			<Material PartID="1527401" Unit="EA" Qty="4" />
			<Material PartID="1527402" Unit="EA" Qty="4" />
			<Material PartID="8026865" Unit="EA" Qty="1" />
			<Material PartID="8026870-1" Unit="EA" Qty="1" />
			<Material PartID="8026870-2" Unit="EA" Qty="1" />
			<Material PartID="1112801" Unit="EA" Qty="2" />
			<Material PartID="8025092" Unit="EA" Qty="1" />
			<Material PartID="8026868" Unit="EA" Qty="1" />
			<Material PartID="1477203-1" Unit="EA" Qty="2" />
			<Material PartID="6372013" Unit="EA" Qty="2" />
			<Material PartID="8026875" Unit="EA" Qty="2" />
			<Material PartID="8026871-1" Unit="EA" Qty="2" />
			<Material PartID="8026869" Unit="EA" Qty="2" />
			<Material PartID="1210902" Unit="EA" Qty="2" />
			<Material PartID="1575501" Unit="EA" Qty="4" />
			<Material PartID="1210903" Unit="EA" Qty="2" />
			<Material PartID="6372037" Unit="EA" Qty="4" />
			<Material PartID="1182401" Unit="EA" Qty="4" />
			<Material PartID="8026867" Unit="EA" Qty="1" />
			<Material PartID="8026864" Unit="EA" Qty="1" />
			<Material PartID="1577201" Unit="EA" Qty="1" />
			<Material PartID="1507201" Unit="EA" Qty="1" />
			<Material PartID="8026873" Unit="EA" Qty="1" />
			<Material PartID="8026872" Unit="EA" Qty="2" />
			<Material PartID="1421703" Unit="EA" Qty="8" />
			<Material PartID="1506101" Unit="EA" Qty="8" />
			<Material PartID="1576101" Unit="EA" Qty="8" />
			<Material PartID="1507301" Unit="EA" Qty="2" />
			<Material PartID="1577309" Unit="EA" Qty="2" />
		</Operation>
	</Part>
	
	<Part PartID="M266">
		<Operation WC="ASY010">
			<Material PartID="8025092" Unit="EA" Qty="1" />
			<Material PartID="8026864" Unit="EA" Qty="1" />
			<Material PartID="8026867" Unit="EA" Qty="1" />
			<Material PartID="8026868" Unit="EA" Qty="1" />
			<Material PartID="8026869" Unit="EA" Qty="2" />
			<Material PartID="8026870-1" Unit="EA" Qty="1" />
			<Material PartID="8026870-2" Unit="EA" Qty="1" />
			<Material PartID="8026871-2" Unit="EA" Qty="2" />
			<Material PartID="8026872" Unit="EA" Qty="2" />
			<Material PartID="8026873" Unit="EA" Qty="1" />
			<Material PartID="8026875" Unit="EA" Qty="2" />
			<Material PartID="8033662" Unit="EA" Qty="1" />
			<Material PartID="8033663" Unit="EA" Qty="2" />
			<Material PartID="8033664" Unit="EA" Qty="2" />
			<Material PartID="8033769" Unit="EA" Qty="6" />
			<Material PartID="1210902" Unit="EA" Qty="2" />
			<Material PartID="1210903" Unit="EA" Qty="2" />
			<Material PartID="1575501" Unit="EA" Qty="4" />
			<Material PartID="1231702-1" Unit="EA" Qty="8" />
			<Material PartID="1231703" Unit="EA" Qty="8" />
			<Material PartID="1576101" Unit="EA" Qty="8" />
			<Material PartID="1506101" Unit="EA" Qty="8" />
			<Material PartID="1402005" Unit="EA" Qty="4" />
			<Material PartID="1577201" Unit="EA" Qty="5" />
			<Material PartID="1527201" Unit="EA" Qty="5" />
			<Material PartID="1477203-1" Unit="EA" Qty="2" />
			<Material PartID="1232420" Unit="EA" Qty="4" />
			<Material PartID="1577301" Unit="EA" Qty="2" />
			<Material PartID="1507301" Unit="EA" Qty="2" />
			<Material PartID="1112801" Unit="EA" Qty="2" />
			<Material PartID="1527401" Unit="EA" Qty="4" />
			<Material PartID="1527402" Unit="EA" Qty="4" />
			<Material PartID="6331001" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/8033334_HD Drive Unit.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8033334"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8026576">
		<Operation WC="ASY010">
			<Material PartID="8026535" Unit="EA" Qty="1" />
			<Material PartID="6090013" Unit="EA" Qty="2" />
		</Operation>
	</Part>
	
	<Part PartID="8026535">
		<Operation WC="EXT010">
			<Material PartID="8026507" Unit="EA" Qty="1" />
			<Material PartID="8026535-A" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="EXT010">
			<Material PartID="8026535-B" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026507">
		<Operation WC="EXT010">
			<Material PartID="8026507-U" Unit="EA" Qty="1" />
			<Material PartID="9816101" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026575">
		<Operation WC="ASY010">
			<Material PartID="8026506" Unit="EA" Qty="1" />
			<Material PartID="8026576" Unit="EA" Qty="1" />
			<Material PartID="1102801" Unit="EA" Qty="1" />
			<Material PartID="8026505" Unit="EA" Qty="1" />
			<Material PartID="1033501" Unit="EA" Qty="1" />
			<Material PartID="1527601" Unit="EA" Qty="2" />
			<Material PartID="1527602" Unit="EA" Qty="1" />
			<Material PartID="2477626-1" Unit="EA" Qty="1" />
			<Material PartID="1211203" Unit="EA" Qty="2" />
			<Material PartID="1011201" Unit="EA" Qty="2" />
			<Material PartID="1575701" Unit="EA" Qty="2" />
			<Material PartID="8033976" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8033976">
		<Operation WC="MCH030">
			<Material PartID="6092022" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026574">
		<Operation WC="ASY010">
			<Material PartID="6620009" Unit="EA" Qty="1" />
			<Material PartID="6140094" Unit="EA" Qty="1" />
			<Material PartID="8026533" Unit="EA" Qty="1" />
			<Material PartID="1422008" Unit="EA" Qty="4" />
			<Material PartID="1577201" Unit="EA" Qty="4" />
			<Material PartID="2332803" Unit="EA" Qty="2" />
			<Material PartID="6460040-U" Unit="IN" Qty="1" Size="1.500" />
			<Material PartID="6460040-U" Unit="IN" Qty="1" Size="2.500"/>
		</Operation>
	</Part>
	
	<Part PartID="8033317">
		<Operation WC="FAB010">
			<Material PartID="9070060-316" Unit="IN" Qty="1" Size="5.000" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="803330-A">
		<Operation WC="FAB090">
			<Material PartID="6741022" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="FAB100" />
	</Part>
	
	<Part PartID="8033327">
		<Operation WC="FAB010">
			<Material PartID="9073040-049" Unit="IN" Qty="1" Size="1.554" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8033330">
		<Operation WC="ASY010">
			<Material PartID="8033329" Unit="EA" Qty="1" />
			<Material PartID="8033317" Unit="EA" Qty="1" />
			<Material PartID="8033327" Unit="EA" Qty="1" />
			<Material PartID="803330-A" Unit="EA" Qty="1" />
			<Material PartID="8026600" Unit="EA" Qty="2" />
			<Material PartID="1477202" Unit="EA" Qty="1" />
			<Material PartID="3030019" Unit="EA" Qty="4" />
			<Material PartID="1001701" Unit="EA" Qty="1" />
			<Material PartID="1402820" Unit="EA" Qty="1" />
			<Material PartID="1402824" Unit="EA" Qty="1" />
			<Material PartID="1527401" Unit="EA" Qty="3" />
			<Material PartID="1527402" Unit="EA" Qty="1" />
			<Material PartID="1577401" Unit="EA" Qty="2" />
			<Material PartID="1032801" Unit="EA" Qty="1" />
			<Material PartID="6090005" Unit="EA" Qty="4" />
			<Material PartID="6680010" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="6140094">
		<Operation WC="EXT010">
			<Material PartID="6140094-U" Unit="EA" Qty="1" />
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="6620009">
		<Operation WC="EXT010">
			<Material PartID="6620009-U" Unit="EA" Qty="1" />
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026533">
		<Operation WC="EXT010">
			<Material PartID="8026533-U" Unit="EA" Qty="1" />
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8033334">
		<Operation WC="ASY010">
			<Material PartID="8927876" Unit="EA" Qty="1" />
			<Material PartID="1210902" Unit="EA" Qty="2" />
			<Material PartID="1575501" Unit="EA" Qty="2" />
			<Material PartID="8025103" Unit="EA" Qty="1" />
			<Material PartID="6110001" Unit="EA" Qty="1" />
			<Material PartID="8026509" Unit="EA" Qty="1" />
			<Material PartID="6090019" Unit="EA" Qty="2" />
			<Material PartID="1402808" Unit="EA" Qty="4" />
			<Material PartID="1032801" Unit="EA" Qty="7" />
			<Material PartID="1577401" Unit="EA" Qty="7" />
			<Material PartID="8026575" Unit="EA" Qty="1" />
			<Material PartID="1231703" Unit="EA" Qty="8" />
			<Material PartID="1576101" Unit="EA" Qty="8" />
			<Material PartID="1506101" Unit="EA" Qty="8" />
			<Material PartID="8033330" Unit="EA" Qty="1" />
			<Material PartID="1211404" Unit="EA" Qty="2" />
			<Material PartID="1033001" Unit="EA" Qty="2" />
			<Material PartID="1575901" Unit="EA" Qty="2" />
			<Material PartID="8033369" Unit="EA" Qty="1" />
			<Material PartID="8026574" Unit="EA" Qty="1" />
			<Material PartID="1162801" Unit="EA" Qty="2" />
			<Material PartID="1527401" Unit="EA" Qty="2" />
			<Material PartID="1507401" Unit="EA" Qty="2" />
		</Operation>
	</Part>
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/8025043-1.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8025043-1-X"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8025042">
		<Operation WC="ASY010">
			<Material PartID="8025042-A" Unit="EA" Qty="1" />
		</Operation>	
		<Operation WC="EXT010">
			<Material PartID="9816002" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="3110004" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8025043-1">
		<Operation WC="ASY010">
			<Material PartID="6680001" Unit="EA" Qty="4" />
			<Material PartID="6230007-1" Unit="EA" Qty="4" />
			<Material PartID="2033501" Unit="EA" Qty="4" />
			<Material PartID="3031003" Unit="EA" Qty="4" />
			<Material PartID="2577401" Unit="EA" Qty="4" />
			<Material PartID="2402812" Unit="EA" Qty="4" />
			<Material PartID="8025044-1" Unit="EA" Qty="4" />
			<Material PartID="8025042" Unit="EA" Qty="4" />
		</Operation>
	</Part>

</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/M45-9.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M45-9"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8025779-2A">
		<Operation WC="FAB010">
			<Material PartID="9192162" Unit="IN" Qty="1" Size="0.375" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8025779-2">
		<Operation WC="EXT010">
			<Material PartID="8025779-2A" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026315-A">
		<Operation WC="FAB010">
			<Material PartID="9192162" Unit="IN" Qty="1" Size="0.375" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026315">
		<Operation WC="EXT010">
			<Material PartID="8026315-A" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8025770-A">
		<Operation WC="FAB010">
			<Material PartID="9192137" Unit="IN" Qty="1" Size="0.500" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8025770">
		<Operation WC="EXT010">
			<Material PartID="8025770-A" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8025818-1">
		<Operation WC="EXT010">
			<Material PartID="6092024" Unit="EA" Qty="1" />
			<Material PartID="8025818-1A" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8025818-2">
		<Operation WC="EXT010">
			<Material PartID="6092024" Unit="EA" Qty="1" />
			<Material PartID="8025818-2A" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8025818-3">
		<Operation WC="EXT010">
			<Material PartID="6092076" Unit="IN" Qty="1" Size="3.00" />
			<Material PartID="8025818-3A" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8025822">
		<Operation WC="EXT010">
			<Material PartID="6332001" Unit="EA" Qty="1" />
			<Material PartID="8025822-A" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027064">
		<Operation WC="MCH030">
			<Material PartID="6332006" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8027060">
		<Operation WC="MCH030">
			<Material PartID="1331404" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8025825-1">
		<Operation WC="FAB010">
			<Material PartID="9092025-1" Unit="IN" Qty="1" Size="3.4375" />
		</Operation>
		<Operation WC="MCH030" />
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8025825-2">
		<Operation WC="FAB010">
			<Material PartID="9092025-1" Unit="IN" Qty="1" Size="3.4375" />
		</Operation>
		<Operation WC="MCH030" />
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8025787-X">
		<Operation WC="ASY010">
			<Material PartID="8025771-1" Unit="EA" Qty="1" />
			<Material PartID="8025771-2" Unit="EA" Qty="1" />
			<Material PartID="8025775" Unit="EA" Qty="2" />
			<Material PartID="8025782" Unit="EA" Qty="2" />
			<Material PartID="8025772" Unit="EA" Qty="2" />
			<Material PartID="8025784" Unit="EA" Qty="2" />
			<Material PartID="8025783" Unit="EA" Qty="1" />
			<Material PartID="8025793" Unit="EA" Qty="1" />
			<Material PartID="8025792" Unit="EA" Qty="1" />
			<Material PartID="8025777" Unit="EA" Qty="1" />
			<Material PartID="8025763" Unit="EA" Qty="1" />
			<Material PartID="8025770" Unit="EA" Qty="1" />
			<Material PartID="8025780" Unit="EA" Qty="1" />
			<Material PartID="8025788" Unit="EA" Qty="1" />
			<Material PartID="8025818-1" Unit="EA" Qty="1" />
			<Material PartID="8025818-2" Unit="EA" Qty="1" />
			<Material PartID="8025818-3" Unit="EA" Qty="1" />
			<Material PartID="8025819" Unit="EA" Qty="1" />
			<Material PartID="8025820" Unit="EA" Qty="1" />
			<Material PartID="8025821" Unit="EA" Qty="1" />
			<Material PartID="8025822" Unit="EA" Qty="1" />
			<Material PartID="8027064" Unit="EA" Qty="1" />
			<Material PartID="8027060" Unit="EA" Qty="1" />
			<Material PartID="8025785" Unit="EA" Qty="1" />
			<Material PartID="8010002" Unit="EA" Qty="1" />
			<Material PartID="6092007" Unit="EA" Qty="1" />
			<Material PartID="1702001" Unit="IN" Qty="4" Size="1.625" />
			<Material PartID="6370004" Unit="EA" Qty="2" />
			<Material PartID="1331404-1" Unit="EA" Qty="3" />
			<Material PartID="1527202" Unit="EA" Qty="6" />
			<Material PartID="1577201" Unit="EA" Qty="4" />
			<Material PartID="1032001" Unit="EA" Qty="7" />
			<Material PartID="6094005" Unit="EA" Qty="2" />
			<Material PartID="2331703" Unit="EA" Qty="2" />
			<Material PartID="1043601" Unit="EA" Qty="4" />
			<Material PartID="6370008" Unit="EA" Qty="2" />
			<Material PartID="3030006" Unit="EA" Qty="4" />
			<Material PartID="1402408" Unit="EA" Qty="2" />
			<Material PartID="1577301" Unit="EA" Qty="8" />
			<Material PartID="1527301" Unit="EA" Qty="8" />
			<Material PartID="1422014-1" Unit="EA" Qty="4" />
			<Material PartID="1232406" Unit="EA" Qty="4" />
			<Material PartID="1210902" Unit="EA" Qty="4" />
			<Material PartID="1575501" Unit="EA" Qty="15" />
			<Material PartID="1210903" Unit="EA" Qty="4" />
			<Material PartID="1210904" Unit="EA" Qty="2" />
			<Material PartID="3402008" Unit="EA" Qty="2" />
			<Material PartID="1042001" Unit="EA" Qty="12" />
			<Material PartID="1402412" Unit="EA" Qty="2" />
			<Material PartID="1402006" Unit="EA" Qty="2" />
			<Material PartID="1421703" Unit="EA" Qty="6" />
			<Material PartID="1576101" Unit="EA" Qty="10" />
			<Material PartID="1231703" Unit="EA" Qty="4" />
			<Material PartID="6092008" Unit="EA" Qty="1" />
			<Material PartID="1231203" Unit="EA" Qty="4" />
			<Material PartID="6370005" Unit="EA" Qty="2" />
			<Material PartID="2331402" Unit="EA" Qty="2" />
			<Material PartID="3402014" Unit="EA" Qty="1" />
			<Material PartID="3010020" Unit="EA" Qty="2" />
			<Material PartID="6750006" Unit="EA" Qty="1" />
			<Material PartID="6094003" Unit="EA" Qty="2" />
			<Material PartID="6093007" Unit="EA" Qty="2" />
			<Material PartID="1331702" Unit="EA" Qty="3" />
			<Material PartID="6230005" Unit="EA" Qty="1" />
			<Material PartID="1000901" Unit="EA" Qty="6" />
			<Material PartID="1455102" Unit="EA" Qty="4" />
			<Material PartID="1252004" Unit="EA" Qty="2" />
			<Material PartID="1210908" Unit="EA" Qty="2" />
			<Material PartID="1567201" Unit="EA" Qty="4" />
		</Operation>
	</Part>
	
	<Part PartID="M45-9">
		<Operation WC="ASY010">
			<Material PartID="8025787-X" Unit="EA" Qty="1" />
			<Material PartID="8025779-2" Unit="EA" Qty="2" />
			<Material PartID="8025778" Unit="EA" Qty="2" />
			<Material PartID="8025773" Unit="EA" Qty="2" />
			<Material PartID="8025781" Unit="EA" Qty="2" />
			<Material PartID="8025825-1" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="M45-9R">
		<Operation WC="ASY010">
			<Material PartID="8025787-X" Unit="EA" Qty="1" />
			<Material PartID="8025779-2" Unit="EA" Qty="2" />
			<Material PartID="8025778" Unit="EA" Qty="2" />
			<Material PartID="8025773" Unit="EA" Qty="2" />
			<Material PartID="8029609" Unit="EA" Qty="2" />
			<Material PartID="8025825-2" Unit="EA" Qty="1" />
		</Operation>
	</Part>	
		
	<Part PartID="M45-9M">
		<Operation WC="ASY010">
			<Material PartID="8025787-X" Unit="EA" Qty="1" />
			<Material PartID="8026315" Unit="EA" Qty="2" />
			<Material PartID="8026318" Unit="EA" Qty="2" />
			<Material PartID="8026316" Unit="EA" Qty="2" />
			<Material PartID="8026317" Unit="EA" Qty="2" />
			<Material PartID="8025825-1" Unit="EA" Qty="1" />
		</Operation>
	</Part>	
		
	<Part PartID="M45-9MR">
		<Operation WC="ASY010">
			<Material PartID="8025787-X" Unit="EA" Qty="1" />
			<Material PartID="8026315" Unit="EA" Qty="2" />
			<Material PartID="8026318" Unit="EA" Qty="2" />
			<Material PartID="8026316" Unit="EA" Qty="2" />
			<Material PartID="8026317" Unit="EA" Qty="2" />
			<Material PartID="8025825-2" Unit="EA" Qty="1" />
		</Operation>
	</Part>	
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/Model33M.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="Model 33M"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">

	<Part PartID="8034376">
		<Operation WC="FAB010">
			<Material PartID="9014406-4" Unit="IN" Qty="1" Size="2.1875" />
		</Operation>
		<Operation WC="FAB020" />
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="MCH010" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.0313" />
		</Operation>	
	</Part>
	
	<Part PartID="8034622-1">
		<Operation WC="FAB010">
			<Material PartID="9014204-4" Unit="IN" Qty="1" Size="22" />
		</Operation>
		<Operation WC="FAB020" />
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.0313" />
		</Operation>
	</Part>
	
	<Part PartID="8034622-2">
		<Operation WC="FAB010">
			<Material PartID="9014204-4" Unit="IN" Qty="1" Size="22" />
		</Operation>
		<Operation WC="FAB020" />
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.0313" />
		</Operation>	
	</Part>
	
	<Part PartID="8028312">
		<Operation WC="FAB010">
			<Material PartID="9190201-4" Unit="IN" Qty="1" Size="2.25" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8029125-1">
		<Operation WC="MCH010">
			<Material PartID="5460403" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027958">
		<Operation WC="ASY010">
			<Material PartID="8027958" Unit="EA" Qty="1" />
			<Material PartID="8034376" Unit="EA" Qty="1" />
			<Material PartID="8034622-1" Unit="EA" Qty="1" />
			<Material PartID="8034622-2" Unit="EA" Qty="1" />
			<Material PartID="8028312" Unit="EA" Qty="1" />
			<Material PartID="8029125-1" Unit="EA" Qty="1" />
			<Material PartID="5145601" Unit="EA" Qty="3" />
			<Material PartID="5062601" Unit="EA" Qty="1" />
			<Material PartID="5145603" Unit="EA" Qty="3" />
			<Material PartID="5261607" Unit="EA" Qty="1" />
			<Material PartID="5102601-1" Unit="EA" Qty="1" />
			<Material PartID="5462603" Unit="EA" Qty="1" />
			<Material PartID="5262605" Unit="EA" Qty="1" />
			<Material PartID="5144422" Unit="EA" Qty="4" />
			<Material PartID="5102501" Unit="EA" Qty="1" />
			<Material PartID="5144421" Unit="EA" Qty="1" />
			<Material PartID="5424604" Unit="IN" Qty="96" />
			<Material PartID="5424404" Unit="IN" Qty="96" />
			<Material PartID="5462502" Unit="EA" Qty="1" />
			<Material PartID="5144623" Unit="EA" Qty="1" />
			<Material PartID="5262503" Unit="EA" Qty="1" />
			<Material PartID="5015404" Unit="EA" Qty="1" />
			<Material PartID="5262401" Unit="EA" Qty="1" />
			<Material PartID="5132501" Unit="EA" Qty="1" />
			<Material PartID="5302402" Unit="EA" Qty="1" />
			<Material PartID="5032502" Unit="EA" Qty="1" />
			<Material PartID="5406402" Unit="EA" Qty="1" />
			<Material PartID="5116201" Unit="EA" Qty="1" />
			<Material PartID="6583031" Unit="EA" Qty="1" />
			<Material PartID="5320007" Unit="EA" Qty="1" />
			<Material PartID="5130401" Unit="EA" Qty="1" />
			<Material PartID="5131003" Unit="EA" Qty="1" />
			<Material PartID="5180603" Unit="IN" Qty="60" />
			<Material PartID="5106501" Unit="EA" Qty="1" />
			<Material PartID="5033602" Unit="EA" Qty="1" />
			<Material PartID="5144427" Unit="EA" Qty="1" />
			<Material PartID="5144622" Unit="EA" Qty="3" />
			<Material PartID="5144621" Unit="EA" Qty="2" />
			<Material PartID="5112601" Unit="EA" Qty="1" />
			<Material PartID="5262601" Unit="EA" Qty="1" />
			<Material PartID="2547401" Unit="EA" Qty="8" />
			<Material PartID="6710011" Unit="EA" Qty="4" />
			<Material PartID="7352034" Unit="EA" Qty="1" />
			<Material PartID="5141001" Unit="EA" Qty="8" />
			<Material PartID="5141003" Unit="EA" Qty="8" />
			<Material PartID="2231706" Unit="EA" Qty="1" />
			<Material PartID="2516101" Unit="EA" Qty="1" />
			<Material PartID="2606101" Unit="EA" Qty="1" />
			<Material PartID="2001701" Unit="EA" Qty="1" />
			<Material PartID="2402816" Unit="EA" Qty="4" />
			<Material PartID="2507401" Unit="EA" Qty="8" />
			<Material PartID="2577401" Unit="EA" Qty="4" />
			<Material PartID="2032801" Unit="EA" Qty="4" />
			<Material PartID="2402410" Unit="EA" Qty="4" />
			<Material PartID="2517301" Unit="EA" Qty="4" />
			<Material PartID="2507301" Unit="EA" Qty="4" />
			<Material PartID="2577301" Unit="EA" Qty="4" />
			<Material PartID="2002401" Unit="EA" Qty="4" />
		</Operation>
	</Part>
	
</Parts>
