=== MilesStarr/TACTIC_ERP_Phase2BOM/BOM.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Parts">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Part" type="PartType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Group" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

  <xs:complexType name="PartType">
    <xs:sequence>
      <xs:element name="Operation" type="OperationType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="PartID" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="OperationType">
    <xs:sequence>
      <xs:element name="Material" type="MaterialType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="WC" type="xs:string" default="TACwip"/>
  </xs:complexType>

  <xs:complexType name="MaterialType">
    <xs:attribute name="PartID" type="xs:string" use="required"/>
    <xs:attribute name="Unit" type="xs:string" use="required"/>
    <xs:attribute name="Qty" type="xs:int" use="required"/>
    <xs:attribute name="Size" type="xs:float" use="optional"/>
  </xs:complexType>

  
</xs:schema>

=== MilesStarr/TACTIC_ERP_Phase2BOM/M33H.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M33H"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8029125-2">
		<Operation WC="MCH010">
			<Material PartID="5460501" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8026973-2">
		<Operation WC="FAB010">
			<Material PartID="9014204-4" Unit="In" Qty="1" Size="22" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Qty="1" Unit="Pt" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8026973-2">
		<Operation WC="FAB010">
			<Material PartID="9014204-4" Unit="In" Qty="1" Size="22" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Qty="1" Unit="Pt" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8034547">
		<Operation WC="FAB010">
			<Material PartID="9014245-4" Unit="In" Qty="1" Size="7.500" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="MCH010" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Qty="1" Unit="Pt" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8028312">
		<Operation WC="FAB010">
			<Material PartID="9190201-4" Unit="In" Qty="1" Size="2.250" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="M33H">
		<Operation WC="ASY010">
			<Material PartID="5144623" Unit="EA" Qty="1" />
			<Material PartID="5144625" Unit="EA" Qty="2" />
			<Material PartID="5144622" Unit="EA" Qty="5" />
			<Material PartID="5424604" Unit="IN" Qty="48" />
			<Material PartID="5015404" Unit="EA" Qty="1" />
			<Material PartID="5132501" Unit="EA" Qty="1" />
			<Material PartID="5144621" Unit="EA" Qty="7" />
			<Material PartID="6583031" Unit="EA" Qty="1" />
			<Material PartID="3403501" Unit="EA" Qty="1" />
			<Material PartID="5144628" Unit="EA" Qty="1" />
			<Material PartID="5145603" Unit="EA" Qty="1" />
			<Material PartID="5262501" Unit="EA" Qty="2" />
			<Material PartID="5144626" Unit="EA" Qty="2" />
			<Material PartID="5265501" Unit="EA" Qty="1" />
			<Material PartID="5032402" Unit="EA" Qty="1" />
			<Material PartID="5102401" Unit="EA" Qty="1" />
			<Material PartID="8029125-2" Unit="EA" Qty="1" />
			<Material PartID="5106501" Unit="EA" Qty="1" />
			<Material PartID="5130401" Unit="EA" Qty="2" />
			<Material PartID="5320010" Unit="EA" Qty="1" />
			<Material PartID="5262505" Unit="EA" Qty="1" />
			<Material PartID="5462502" Unit="EA" Qty="1" />
			<Material PartID="5102701" Unit="EA" Qty="1" />
			<Material PartID="5116601" Unit="EA" Qty="1" />
			<Material PartID="5145601" Unit="EA" Qty="3" />
			<Material PartID="5180603" Unit="IN" Qty="96" />
			<Material PartID="5180701" Unit="IN" Qty="24" />
			<Material PartID="5033701" Unit="EA" Qty="2" />
			<Material PartID="5404701" Unit="EA" Qty="2" />
			<Material PartID="5033602" Unit="EA" Qty="1" />
			<Material PartID="5266701" Unit="EA" Qty="1" />
			<Material PartID="5262709" Unit="EA" Qty="2" />
			<Material PartID="5145702" Unit="EA" Qty="2" />
			<Material PartID="5462701" Unit="EA" Qty="1" />
			<Material PartID="8026973-2" Unit="EA" Qty="1" />
			<Material PartID="8026973-1" Unit="EA" Qty="1" />
			<Material PartID="2547401" Unit="EA" Qty="8" />
			<Material PartID="6710011" Unit="EA" Qty="4" />
			<Material PartID="8034547" Unit="EA" Qty="1" />
			<Material PartID="8028312" Unit="EA" Qty="1" />
			<Material PartID="3860028-1" Unit="EA" Qty="2" />
			<Material PartID="5189201" Unit="EA" Qty="4" />
			<Material PartID="5189301" Unit="EA" Qty="2" />
			<Material PartID="5131003" Unit="EA" Qty="1" />
			<Material PartID="2402414" Unit="EA" Qty="6" />
			<Material PartID="2507201" Unit="EA" Qty="12" />
			<Material PartID="2577201" Unit="EA" Qty="6" />
			<Material PartID="2032001" Unit="EA" Qty="6" />
			<Material PartID="2507401" Unit="EA" Qty="12" />
			<Material PartID="2577401" Unit="EA" Qty="8" />
			<Material PartID="2032801" Unit="EA" Qty="8" />
			<Material PartID="2402816" Unit="EA" Qty="4" />
			<Material PartID="2001701" Unit="EA" Qty="3" />
			<Material PartID="2596101" Unit="EA" Qty="3" />
			<Material PartID="2516101" Unit="EA" Qty="6" />
			<Material PartID="2231706" Unit="EA" Qty="3" />
			<Material PartID="9712001" Unit="ml" Qty="10" />
			<Material PartID="9712002" Unit="IN" Qty="24" />
		</Operation>
	</Part>
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/Model76FG_Motor.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M76FG_Motor"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">

	<Part PartID="8035536-X">  <!-- clean -->
		<Operation WC="ASY010">
			<Material PartID="8033392-1" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033392-2" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033389-2" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033389-1" Unit="EA" Qty="2" />  <!-- clean -->
			<Material PartID="8034129" Unit="EA" Qty="4" />  <!-- exists -->
			<Material PartID="8033427" Unit="EA" Qty="4" />  <!-- clean -->
			<Material PartID="8033391" Unit="EA" Qty="4" />  <!-- exists -->
			<Material PartID="8033397" Unit="EA" Qty="1" />  <!-- purchased -->
			<Material PartID="8033396" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033394" Unit="EA" Qty="1" />  <!-- exists -->
			<Material PartID="8033395" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033423" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033393" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="6631673" Unit="EA" Qty="1" />
			<Material PartID="6710010" Unit="EA" Qty="4" />
			<Material PartID="2402008" Unit="EA" Qty="2" />
			<Material PartID="2507201" Unit="EA" Qty="33" />
			<Material PartID="2577201" Unit="EA" Qty="15" />
			<Material PartID="2032001" Unit="EA" Qty="10" />
			<Material PartID="2507401" Unit="EA" Qty="17" />
			<Material PartID="2577401" Unit="EA" Qty="11" />
			<Material PartID="2032801" Unit="EA" Qty="7" />
			<Material PartID="2402820" Unit="EA" Qty="4" />
			<Material PartID="2033501" Unit="EA" Qty="4" />
			<Material PartID="2577601" Unit="EA" Qty="8" />
			<Material PartID="2507601" Unit="EA" Qty="12" />
			<Material PartID="2402004" Unit="EA" Qty="5" />
			<Material PartID="2402010" Unit="EA" Qty="6" />
			<Material PartID="2402012" Unit="EA" Qty="1" />
			<Material PartID="2403536" Unit="EA" Qty="4" />
			<Material PartID="2230903" Unit="EA" Qty="1" />
			<Material PartID="2403510" Unit="EA" Qty="4" />
			<Material PartID="2402822" Unit="EA" Qty="6" />
			<Material PartID="2547601" Unit="EA" Qty="4" />
		</Operation>
	</Part>
	<Part PartID="8035536-1">  <!-- clean -->
		<Operation WC="ASY010">
			<Material PartID="8035536-X" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="7472005" Unit="EA" Qty="1" />
			<Material PartID="8033390-2" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033390-1" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="6830056" Unit="EA" Qty="1" />
			<Material PartID="6140102" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	<Part PartID="8035536-2">  <!-- clean -->
		<Operation WC="ASY010">
			<Material PartID="8035536-X" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="7472007" Unit="EA" Qty="1" />
			<Material PartID="8033390-4" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033390-3" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="6830057" Unit="EA" Qty="1" />
			<Material PartID="6140103" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	<Part PartID="8035536-3">  <!-- clean -->
		<Operation WC="ASY010">
			<Material PartID="8035536-X" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="7472010" Unit="EA" Qty="1" />
			<Material PartID="8033390-4" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="8033390-3" Unit="EA" Qty="1" />  <!-- clean -->
			<Material PartID="6830057" Unit="EA" Qty="1" />
			<Material PartID="6140103" Unit="EA" Qty="1" />
		</Operation>
	</Part>

	<Part PartID="8033392-1">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014507-6" Unit="IN" Qty="1" Size="39.5" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="MCH010" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>
	<Part PartID="8033392-2">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014507-6" Unit="IN" Qty="1" Size="39.5" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="MCH010" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

	<Part PartID="8033389-1">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9015454" Unit="IN" Qty="1" Size="17.5" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="MCH010" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>
	<Part PartID="8033389-2">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9015454" Unit="IN" Qty="1" Size="17.5" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

	<Part PartID="8033427">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9010300-4" Unit="IN" Qty="1" Size="2.75" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

	<Part PartID="8033396">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9015200-1" Unit="IN" Qty="1" Size="26.5" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

	<Part PartID="8033395">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014122-3" Unit="IN" Qty="1" Size="17.875" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

	<Part PartID="8033423">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014122-3" Unit="IN" Qty="1" Size="17.875" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

	<Part PartID="8033393">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014122-3" Unit="IN" Qty="1" Size="23.875" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

	<Part PartID="8033390-1">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014304-6" Unit="IN" Qty="1" Size="38" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>
	<Part PartID="8033390-2">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014304-6" Unit="IN" Qty="1" Size="38" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>
	<Part PartID="8033390-3">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014304-6" Unit="IN" Qty="1" Size="38" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>
	<Part PartID="8033390-4">  <!-- clean -->
		<Operation WC="FAB010">
			<Material PartID="9014304-6" Unit="IN" Qty="1" Size="38" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.125" />
		</Operation>
	</Part>

</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/Safety Whl Ass'y_8026015-X.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8026015-X"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8026016-1">
		<Operation WC="FAB010">
			<Material PartID="9014244-4" Unit="In" Qty="1" Size="12" />
		</Operation>	
		<Operation WC="FAB020" />	
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="FIN010" />
		<Operation WC="EXT010">
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026016-2">
		<Operation WC="FAB010">
			<Material PartID="9014244-4" Unit="In" Qty="1" Size="12" />
		</Operation>	
		<Operation WC="FAB020" />	
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="FIN010" />
		<Operation WC="EXT010">
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026017">
		<Operation WC="FAB010">
			<Material PartID="9014244-4" Unit="IN" Qty="1" Size="3.750" />
		</Operation>
		<Operation WC="FAB020" />
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="MCH010" />
		<Operation WC="FIN010" />
		<Operation WC="EXT010">
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8029500">
		<Operation WC="MCH070">
			<Material PartID="6160014-1" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8029291">
		<Operation WC="ASY010">
			<Material PartID="8029500" Unit="EA" Qty="1" />
			<Material PartID="6160016" Unit="EA" Qty="1" />
			<Material PartID="6160018-1" Unit="EA" Qty="2" />
			<Material PartID="6160017" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026015-X">
		<Operation WC="ASY010">
			<Material PartID="8026017" Unit="EA" Qty="1" />
			<Material PartID="8029291" Unit="EA" Qty="1" />
			<Material PartID="1577301" Unit="EA" Qty="2" />
			<Material PartID="1402405" Unit="EA" Qty="2" />
			<Material PartID="2507401" Unit="EA" Qty="1" />
			<Material PartID="2577401" Unit="EA" Qty="1" />
			<Material PartID="2402808" Unit="EA" Qty="1" />
			<Material PartID="2507301" Unit="EA" Qty="2" />
			<Material PartID="2577301" Unit="EA" Qty="2" />
			<Material PartID="2402406" Unit="EA" Qty="2" />
		</Operation>
	</Part>
	
	<Part PartID="8026015-1">
		<Operation WC="ASY010">
			<Material PartID="8026015-X" Unit="EA" Qty="1" />
			<Material PartID="8026016-1" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8026015-2">
		<Operation WC="ASY010">
			<Material PartID="8026015-X" Unit="EA" Qty="1" />
			<Material PartID="8026016-2" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/M258A.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M258A"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">

	<Part PartID="8034688-1">
		<Operation WC="FAB010">
			<Material PartID="9194122-3" Unit="IN" Qty="1" Size=".625" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8034688-2">
		<Operation WC="FAB010">
			<Material PartID="9194122-3" Unit="IN" Qty="1" Size="1.188" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />
		</Operation>	
	</Part>
	
	<Part PartID="8034688-3">
		<Operation WC="FAB010">
			<Material PartID="9194122-3" Unit="IN" Qty="1" Size="2.750" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />
		</Operation>	
	</Part>
	
	<Part PartID="8034689-A">
		<Operation WC="FAB010">
			<Material PartID="9900004" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8034689-B">
		<Operation WC="FAB010">
			<Material PartID="3703501" Unit="IN" Qty="1" Size="2.730" />
		<Operation WC="MCH060" />	
		</Operation>
	</Part>
	
	<Part PartID="8034689">
		<Operation WC="FAB070">
			<Material PartID="8034689-A" Unit="EA" Qty="1" />
			<Material PartID="8034689-B" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8034693-1">
		<Operation WC="MCH030">
			<Material PartID="1477302-2" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8034693-2">
		<Operation WC="MCH030">
			<Material PartID="1477101-2" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8034687-1">
		<Operation WC="FAB010">
			<Material PartID="9190030-1" Unit="IN" Qty="1" Size="1.605" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />	
		</Operation>
	</Part>
	
	<Part PartID="8034687-2">
		<Operation WC="FAB010">
			<Material PartID="9190030-1" Unit="IN" Qty="1" Size="2.500" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />	
		</Operation>
	</Part>
	
	<Part PartID="8034686">
		<Operation WC="FAB010">
			<Material PartID="9190060-4" Unit="IN" Qty="1" Size="0.875" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />	
		</Operation>
	</Part>
	
	<Part PartID="8025319-17">
		<Operation WC="MCH010">
			<Material PartID="1702001" Unit="IN" Qty="1" Size="1.5" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8034694-1">
		<Operation WC="MCH010">
			<Material PartID="6372019" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8034685">
		<Operation WC="FAB010">
			<Material PartID="9190040-3" Unit="IN" Qty="1" Size="1.000" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />	
		</Operation>
	</Part>
	
	<Part PartID="8034690">
		<Operation WC="FAB010">
			<Material PartID="1702001" Unit="IN" Qty="1" Size="3.250" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH030" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8034870">
		<Operation WC="ASY010">
			<Material PartID="6161009" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="EXT010">
			<Material PartID="8034870-A" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="6092093" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8034843">
		<Operation WC="FAB010">
			<Material PartID="9612137" Unit="IN" Qty="1" Size="0.375" />
		</Operation>
		<Operation WC="MCH030" />
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8034794-2">
		<Operation WC="ASY010">
			<Material PartID="8034843" Unit="EA" Qty="1" />
			<Material PartID="6090028" Unit="EA" Qty="1" />
			<Material PartID="6560001" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8025079">
		<Operation WC="FAB010">
			<Material PartID="9070200-2" Unit="IN" Qty="1" Size="12.000" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8029180-1">
		<Operation WC="FAB010">
			<Material PartID="9070240-6" Unit="IN" Qty="1" Size="1.750" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8029182-1">
		<Operation WC="FAB010">
			<Material PartID="9192175" Unit="IN" Qty="1" Size="0.375" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
	</Part>
	
	<Part PartID="8029183">
		<Operation WC="MCH010">
			<Material PartID="6372040" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8029184">
		<Operation WC="MCH010">
			<Material PartID="6372010" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8029187">
		<Operation WC="FAB010">
			<Material PartID="9192031" Unit="IN" Qty="1" Size="1.157" />
		</Operation>
		<Operation WC="MCH030" />
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8034682-X">
		<Operation WC="ASY010">
			<Material PartID="8034688-1" Unit="EA" Qty="2" />
			<Material PartID="8034688-2" Unit="EA" Qty="1" />
			<Material PartID="8034688-3" Unit="EA" Qty="1" />
			<Material PartID="8034689" Unit="EA" Qty="1" />
			<Material PartID="8034693-1" Unit="EA" Qty="4" />
			<Material PartID="8034693-2" Unit="EA" Qty="6" />
			<Material PartID="8034687-1" Unit="EA" Qty="2" />
			<Material PartID="8034687-2" Unit="EA" Qty="1" />
			<Material PartID="8034686" Unit="EA" Qty="1" />
			<Material PartID="8025319-17" Unit="EA" Qty="1" />
			<Material PartID="6372008" Unit="EA" Qty="1" />
			<Material PartID="8034694-1" Unit="EA" Qty="1" />
			<Material PartID="8034685" Unit="EA" Qty="1" />
			<Material PartID="8034690" Unit="EA" Qty="1" />
			<Material PartID="8034727" Unit="EA" Qty="1" />
			<Material PartID="8034683" Unit="EA" Qty="1" />
			<Material PartID="8025079" Unit="EA" Qty="1" />
			<Material PartID="8029180-1" Unit="EA" Qty="1" />
			<Material PartID="8029182-1" Unit="EA" Qty="1" />
			<Material PartID="8029183" Unit="EA" Qty="1" />
			<Material PartID="8029184" Unit="EA" Qty="1" />
			<Material PartID="8029187" Unit="EA" Qty="1" />
			<Material PartID="1455102" Unit="EA" Qty="2" />
			<Material PartID="1331401-1" Unit="EA" Qty="1" />
			<Material PartID="3030024" Unit="EA" Qty="1" />
			<Material PartID="6741015" Unit="EA" Qty="1" />
			<Material PartID="1240601-1" Unit="EA" Qty="2" />
			<Material PartID="1575401" Unit="EA" Qty="2" />
			<Material PartID="1421706" Unit="EA" Qty="2" />
			<Material PartID="1576101" Unit="EA" Qty="2" />
			<Material PartID="1506101" Unit="EA" Qty="2" />
			<Material PartID="3030027" Unit="EA" Qty="7" />
			<Material PartID="1402005" Unit="EA" Qty="2" />
			<Material PartID="1567201" Unit="EA" Qty="6" />
			<Material PartID="1537201" Unit="EA" Qty="2" />
			<Material PartID="1042001" Unit="EA" Qty="4" />
			<Material PartID="1527202" Unit="EA" Qty="1" />
			<Material PartID="3030019" Unit="EA" Qty="1" />
			<Material PartID="1422006" Unit="EA" Qty="4" />
			<Material PartID="6092092" Unit="EA" Qty="1" />
			<Material PartID="1402406" Unit="EA" Qty="3" />
			<Material PartID="1577301" Unit="EA" Qty="2" />
			<Material PartID="1527302" Unit="EA" Qty="1" />
			<Material PartID="3030007" Unit="EA" Qty="4" />
			<Material PartID="1507401" Unit="EA" Qty="2" />
		</Operation>
	</Part>
	
	<Part PartID="M258A-1">
		<Operation WC="ASY010">
			<Material PartID="8034682-X" Unit="EA" Qty="1" />
			<Material PartID="8034870" Unit="EA" Qty="4" />
		</Operation>
	</Part>
	
	<Part PartID="M258A-2">
		<Operation WC="ASY010">
			<Material PartID="8034682-X" Unit="EA" Qty="1" />
			<Material PartID="8034794-2" Unit="EA" Qty="4" />
		</Operation>
	</Part>
	
</Parts>
