=== MilesStarr/TACTIC_ERP_Phase2BOM/BOM.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Parts">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Part" type="PartType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Group" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

  <xs:complexType name="PartType">
    <xs:sequence>
      <xs:element name="Operation" type="OperationType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="PartID" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="OperationType">
    <xs:sequence>
      <xs:element name="Material" type="MaterialType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="WC" type="xs:string" default="TACwip"/>
  </xs:complexType>

  <xs:complexType name="MaterialType">
    <xs:attribute name="PartID" type="xs:string" use="required"/>
    <xs:attribute name="Unit" type="xs:string" use="required"/>
    <xs:attribute name="Qty" type="xs:int" use="required"/>
    <xs:attribute name="Size" type="xs:float" use="optional"/>
  </xs:complexType>

  
</xs:schema>

=== MilesStarr/TACTIC_ERP_Phase2BOM/8035422-X_Control Box.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8035422-X"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8035426-1">
		<Operation WC="ELC010">
			<Material PartID="7135201" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812004" Unit="PT" Qty="1" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8035426-2">
		<Operation WC="ELC010">
			<Material PartID="7135201" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812004" Unit="PT" Qty="1" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8035426-3">
		<Operation WC="ELC010">
			<Material PartID="7135201" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812004" Unit="PT" Qty="1" Size=".125" />
		</Operation>
	</Part>
	
	<Part PartID="8035424">
		<Operation WC="ELC010">
			<Material PartID="8035425" Unit="EA" Qty="1" />
			<Material PartID="7163610" Unit="EA" Qty="2" />
			<Material PartID="7163522" Unit="EA" Qty="2" />
			<Material PartID="7163410" Unit="EA" Qty="5" />
			<Material PartID="7160747" Unit="EA" Qty="1" />
			<Material PartID="7240018" Unit="EA" Qty="1" />
			<Material PartID="7305210" Unit="EA" Qty="1" />
			<Material PartID="7689001" Unit="EA" Qty="2" />
			<Material PartID="7303112" Unit="EA" Qty="1" />
			<Material PartID="7446013" Unit="EA" Qty="1" />
			<Material PartID="7683006" Unit="EA" Qty="1" />
			<Material PartID="7574011" Unit="EA" Qty="1" />
			<Material PartID="7574012" Unit="EA" Qty="1" />
			<Material PartID="7195254" Unit="EA" Qty="2" />
			<Material PartID="7195256" Unit="EA" Qty="1" />
			<Material PartID="7195264" Unit="EA" Qty="2" />
			<Material PartID="7195266" Unit="EA" Qty="1" />
			<Material PartID="7195260" Unit="EA" Qty="14" />
			<Material PartID="7524012" Unit="EA" Qty="2" />
			<Material PartID="7683005" Unit="EA" Qty="2" />
			<Material PartID="7820014" Unit="EA" Qty="2" />
			<Material PartID="7640110" Unit="EA" Qty="2" />
			<Material PartID="7640210" Unit="EA" Qty="2" />
			<Material PartID="7640147" Unit="EA" Qty="2" />
			<Material PartID="7640247" Unit="EA" Qty="2" />
			<Material PartID="7801009" Unit="EA" Qty="1" />
			<Material PartID="7772068" Unit="EA" Qty="5" />
			<Material PartID="7810001" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8035239">
		<Operation WC="FAB010">
			<Material PartID="9014305-4" Unit="IN" Qty="1" Size="5.000" />
		</Operation>
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8035422-X">
		<Operation WC="ELC010">
			<Material PartID="8035424-1" Unit="EA" Qty="1" />
			<Material PartID="7890039" Unit="EA" Qty="1" />
			<Material PartID="7890005" Unit="EA" Qty="1" />
			<Material PartID="7631250" Unit="EA" Qty="1" />
			<Material PartID="7350015" Unit="EA" Qty="1" />
			<Material PartID="7352034" Unit="EA" Qty="2" />
			<Material PartID="3051003" Unit="EA" Qty="1" />
			<Material PartID="3054001" Unit="EA" Qty="3" />
			<Material PartID="7195264" Unit="EA" Qty="1" />
			<Material PartID="7195266" Unit="EA" Qty="1" />
			<Material PartID="7195260" Unit="EA" Qty="7" />
			<Material PartID="7960067" Unit="EA" Qty="1" />
			<Material PartID="2361202" Unit="EA" Qty="4" />
			<Material PartID="1241204" Unit="EA" Qty="3" />
			<Material PartID="2032001" Unit="EA" Qty="4" />
			<Material PartID="2595701" Unit="EA" Qty="7" />
			<Material PartID="2001201" Unit="EA" Qty="3" />
			<Material PartID="2505701" Unit="EA" Qty="6" />
			<Material PartID="2231203" Unit="EA" Qty="4" />
			<Material PartID="2402008" Unit="EA" Qty="4" />
			<Material PartID="2507201" Unit="EA" Qty="8" />
			<Material PartID="2577201" Unit="EA" Qty="4" />
			<Material PartID="2032001" Unit="EA" Qty="4" />
			<Material PartID="8035239" Unit="EA" Qty="1" />
			<Material PartID="2507201" Unit="EA" Qty="2" />
			<Material PartID="2577201" Unit="EA" Qty="2" />
			<Material PartID="2402006" Unit="EA" Qty="2" />
			<Material PartID="787100K" Unit="IN" Qty="1" Size="96" />
			<Material PartID="787199K" Unit="IN" Qty="1" Size="48" />
			<Material PartID="787155K" Unit="IN" Qty="1" Size="48" />
			<Material PartID="787111K" Unit="IN" Qty="1" Size="96" />
			<Material PartID="787166K" Unit="IN" Qty="1" Size="72" />
			<Material PartID="787122K" Unit="IN" Qty="1" Size="108" />
			<Material PartID="787100M" Unit="IN" Qty="1" Size="24" />
		</Operation>
	</Part>
	
	<Part PartID="8035422-1">
		<Operation WC="ELC010">
			<Material PartID="8035422-X" Unit="EA" Qty="1" />
			<Material PartID="8035426-1" Unit="EA" Qty="1" />
			<Material PartID="8027536-1" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8035422-2">
		<Operation WC="ELC010">
			<Material PartID="8035422-X" Unit="EA" Qty="1" />
			<Material PartID="8035426-2" Unit="EA" Qty="1" />
			<Material PartID="8027536-8" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8035422-3">
		<Operation WC="ELC010">
			<Material PartID="8035422-X" Unit="EA" Qty="1" />
			<Material PartID="8035426-3" Unit="EA" Qty="1" />
			<Material PartID="8027536-1" Unit="EA" Qty="1" />
			<Material PartID="8027536-8" Unit="EA" Qty="1" />
			<Material PartID="7890039" Unit="EA" Qty="1" />
			<Material PartID="7631250" Unit="EA" Qty="1" />
			<Material PartID="7350015" Unit="EA" Qty="1" />
			<Material PartID="7195264" Unit="EA" Qty="1" />
			<Material PartID="7195260" Unit="EA" Qty="5" />
			<Material PartID="7960067" Unit="EA" Qty="1" />
			<Material PartID="1241204" Unit="EA" Qty="2" />
			<Material PartID="2595701" Unit="EA" Qty="2" />
			<Material PartID="2001201" Unit="EA" Qty="2" />
			<Material PartID="2505701" Unit="EA" Qty="2" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/8025737-X.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8025737-X"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8025733">
		<Operation WC="FAB020">
			<Material PartID="8025005" Unit="EA" Qty="1" />
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />	
		</Operation>
	</Part>
	
	<Part PartID="8034879">
		<Operation WC="FAB010">
			<Material PartID="9610200-5" Unit="IN" Qty="1" Size="2.75" />
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />	
		</Operation>
	</Part>

	<Part PartID="8025732-1">
		<Operation WC="FAB010">
			<Material PartID="9610200-5" Unit="IN" Qty="1" Size="2.75" />
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />	
		</Operation>
	</Part>

	<Part PartID="8025737-2">
		<Operation WC="ASY010">
			<Material PartID="8034879" Unit="EA" Qty="1" />
			<Material PartID="8025733" Unit="EA" Qty="1" />
			<Material PartID="1231707" Unit="EA" Qty="2" />
			<Material PartID="1506101" Unit="EA" Qty="2" />
			<Material PartID="1575101" Unit="EA" Qty="2" />
		</Operation>
	</Part>
	
	<Part PartID="8025737-1">
		<Operation WC="ASY010">
			<Material PartID="8025732-1" Unit="EA" Qty="1" />
			<Material PartID="1231707" Unit="EA" Qty="2" />
			<Material PartID="1506101" Unit="EA" Qty="2" />
			<Material PartID="1575101" Unit="EA" Qty="2" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/M105-X.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M-105-X"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8034756">
		<Operation WC="FAB010">
			<Material PartID="9014204-3" Unit="IN" Qty="1" Size="2.500" />
		</Operation>
		<Operation WC="FAB020" />
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="8034025">
		<Operation WC="ASY010">
			<Material PartID="6092091" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8034022">
		<Operation WC="FAB010">
			<Material PartID="9014406-4" Unit="IN" Qty="1" Size="6.750" />
		</Operation>
		<Operation WC="FAB020" />
		<Operation WC="FAB030" />
		<Operation WC="FAB040" />
		<Operation WC="FAB080" />
		<Operation WC="MCH010" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size=".0625" />
		</Operation>
	</Part>
	
	<Part PartID="M-105-X">
		<Operation WC="ASY010">
			<Material PartID="2507201" Unit="EA" Qty="14" />
			<Material PartID="2577201" Unit="EA" Qty="10" />
			<Material PartID="2032001" Unit="EA" Qty="8" />
			<Material PartID="2402006" Unit="EA" Qty="4" />
			<Material PartID="2402004" Unit="EA" Qty="2" />
			<Material PartID="6621013" Unit="EA" Qty="1" />
			<Material PartID="6140008" Unit="EA" Qty="1" />
			<Material PartID="8034023-1" Unit="EA" Qty="1" />
			<Material PartID="1421705" Unit="EA" Qty="4" />
			<Material PartID="1576101" Unit="EA" Qty="4" />
			<Material PartID="7960058" Unit="EA" Qty="1" />
			<Material PartID="7194035" Unit="EA" Qty="1" />
			<Material PartID="7194904" Unit="EA" Qty="1" />
			<Material PartID="5180201" Unit="IN" Qty="1" Size="2.500" />
			<Material PartID="6111009" Unit="EA" Qty="1" />
			<Material PartID="8034025" Unit="EA" Qty="1" />
			<Material PartID="8034022" Unit="EA" Qty="1" />
			<Material PartID="8034756" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="M-105-1">
		<Operation WC="ASY010">
			<Material PartID="M-105-X" Unit="EA" Qty="1" />
			<Material PartID="2402008" Unit="EA" Qty="2" />
			<Material PartID="6140007" Unit="EA" Qty="1" />
			<Material PartID="8026139-158" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="M-105-2">
		<Operation WC="ASY010">
			<Material PartID="M-105-X" Unit="EA" Qty="1" />
			<Material PartID="2402012" Unit="EA" Qty="2" />
			<Material PartID="6140011" Unit="EA" Qty="1" />
			<Material PartID="8026139-1" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="M-105-3">
		<Operation WC="ASY010">
			<Material PartID="M-105-3" Unit="EA" Qty="1" />
			<Material PartID="2402008" Unit="EA" Qty="2" />
			<Material PartID="6140007" Unit="EA" Qty="1" />
			<Material PartID="8026139-159" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="M-105-4">
		<Operation WC="ASY010">
			<Material PartID="M-105-X" Unit="EA" Qty="1" />
			<Material PartID="2402008" Unit="EA" Qty="2" />
			<Material PartID="6140007" Unit="EA" Qty="1" />
			<Material PartID="8026139-135" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="M-105-5">
		<Operation WC="ASY010">
			<Material PartID="M-105-X" Unit="EA" Qty="1" />
			<Material PartID="2402008" Unit="EA" Qty="2" />
			<Material PartID="6140007" Unit="EA" Qty="1" />
			<Material PartID="8026139-160" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="M-105-6">
		<Operation WC="ASY010">
			<Material PartID="M-105-X" Unit="EA" Qty="1" />
			<Material PartID="2402008" Unit="EA" Qty="2" />
			<Material PartID="6140007" Unit="EA" Qty="1" />
			<Material PartID="8026139-157" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/Prewetter Ass'y_8027220.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8027220-X"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8027160">
		<Operation WC="FAB010">
			<Material PartID="9014304-3" Unit="IN" Qty="1" Size="1.500" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.0625" />
		</Operation>
	</Part>
	
	<Part PartID="8029309">
		<Operation WC="FAB010">
			<Material PartID="9010100-4" Unit="IN" Qty="1" Size="1.500" />
		</Operation>
		<Operation WC="FAB020" />	
		<Operation WC="FAB030" />	
		<Operation WC="FAB040" />	
		<Operation WC="FIN010" />
		<Operation WC="FIN020">
			<Material PartID="9812001" Unit="PT" Qty="1" Size="0.0625" />
		</Operation>	
	</Part>
	
	<Part PartID="8026497-1">
		<Operation WC="FAB010">
			<Material PartID="1702001" Unit="IN" Qty="1" Size="1.813" />
		</Operation>
		<Operation WC="MCH060" />
		<Operation WC="ASY010">
			<Material PartID="6372010" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="FAB070" />
	</Part>
	
	<Part PartID="8026497-2">
		<Operation WC="FAB010">
			<Material PartID="1702001" Unit="IN" Qty="1" Size="2.813" />
		</Operation>
		<Operation WC="MCH060" />
		<Operation WC="ASY010">
			<Material PartID="6372010" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="FAB070" />
	</Part>
	
	<Part PartID="8027095">
		<Operation WC="FAB010">
			<Material PartID="9900002" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8029301">
		<Operation WC="FAB010">
			<Material PartID="9900002" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027220-X">
		<Operation WC="ASY010">
			<Material PartID="5465209" Unit="EA" Qty="1" />
			<Material PartID="8027160" Unit="EA" Qty="1" />
			<Material PartID="2231708" Unit="EA" Qty="2" />
			<Material PartID="2516101" Unit="EA" Qty="4" />
			<Material PartID="2606101" Unit="EA" Qty="2" />
			<Material PartID="2001701" Unit="EA" Qty="2" />
			<Material PartID="1402404" Unit="EA" Qty="2" />
			<Material PartID="1577301" Unit="EA" Qty="2" />
			<Material PartID="1527302" Unit="EA" Qty="2" />
			<Material PartID="9733001" Unit="G" Qty="1" Size="5" />
			<Material PartID="1577201" Unit="EA" Qty="1" />
			<Material PartID="1537201" Unit="EA" Qty="1" />
			<Material PartID="5424201" Unit="IN" Qty="1" Size="48" />
			<Material PartID="5144226" Unit="EA" Qty="1" />
		</Operation>	
	</Part>
	
	<Part PartID="8027220-1">
		<Operation WC="FAB080">
			<Material PartID="8027200" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="8027220-X" Unit="EA" Qty="1" />
			<Material PartID="5106201" Unit="EA" Qty="1" />
			<Material PartID="8033115" Unit="EA" Qty="1" />
			<Material PartID="8026497-2" Unit="EA" Qty="1" />
			<Material PartID="8027095" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027220-2">
		<Operation WC="FAB080">
			<Material PartID="8027200" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="8027220-X" Unit="EA" Qty="1" />
			<Material PartID="5106201" Unit="EA" Qty="1" />
			<Material PartID="8035491" Unit="EA" Qty="1" />
			<Material PartID="8026497-2" Unit="EA" Qty="1" />
			<Material PartID="8027095" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027220-3">
		<Operation WC="FAB080">
			<Material PartID="8027200" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="8027220-X" Unit="EA" Qty="1" />
			<Material PartID="5106201" Unit="EA" Qty="1" />
			<Material PartID="8033115" Unit="EA" Qty="1" />
			<Material PartID="8026497-2" Unit="EA" Qty="1" />
			<Material PartID="8027095" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027220-4">
		<Operation WC="FAB080">
			<Material PartID="8027200" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="8027220-X" Unit="EA" Qty="1" />
			<Material PartID="5106201" Unit="EA" Qty="1" />
			<Material PartID="8035491" Unit="EA" Qty="1" />
			<Material PartID="8026497-2" Unit="EA" Qty="1" />
			<Material PartID="8027095" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027220-5">
		<Operation WC="FAB080">
			<Material PartID="8027200" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="8027220-X" Unit="EA" Qty="1" />
			<Material PartID="8027201" Unit="EA" Qty="1" />
			<Material PartID="8026497-1" Unit="EA" Qty="1" />
			<Material PartID="8027095" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027220-6">
		<Operation WC="FAB080">
			<Material PartID="8027300" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="8027220-X" Unit="EA" Qty="1" />
			<Material PartID="8027201" Unit="EA" Qty="1" />
			<Material PartID="8029309" Unit="EA" Qty="1" />
			<Material PartID="8026497-1" Unit="EA" Qty="1" />
			<Material PartID="8029301" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027220-7">
		<Operation WC="FAB080">
			<Material PartID="8027200" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="8027220-X" Unit="EA" Qty="1" />
			<Material PartID="8027201" Unit="EA" Qty="1" />
			<Material PartID="8026497-1" Unit="EA" Qty="1" />
			<Material PartID="8027095" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/8026007_Tank Mtg Rail.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8026007_Tank Mtg Rail"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8033647">
		<Operation WC="FAB010">
			<Material PartID="9070300-4" Unit="IN" Qty="1" Size="13.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8033646">
		<Operation WC="FAB010">
			<Material PartID="9074122-3" Unit="IN" Qty="1" Size="13.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8025796">
		<Operation WC="FAB010">
			<Material PartID="9070300-4" Unit="IN" Qty="1" Size="14" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8025791">
		<Operation WC="FAB010">
			<Material PartID="9074122-3" Unit="IN" Qty="1" Size="14" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8026343">
		<Operation WC="FAB010">
			<Material PartID="9070300-4" Unit="IN" Qty="1" Size="20.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8025791">
		<Operation WC="FAB010">
			<Material PartID="9074122-3" Unit="IN" Qty="1" Size="20.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8027541">
		<Operation WC="FAB010">
			<Material PartID="9070300-4" Unit="IN" Qty="1" Size="26.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8027540">
		<Operation WC="FAB010">
			<Material PartID="9074122-3" Unit="IN" Qty="1" Size="26.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8026859">
		<Operation WC="FAB010">
			<Material PartID="9070300-4" Unit="IN" Qty="1" Size="32.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8026858">
		<Operation WC="FAB010">
			<Material PartID="9074122-3" Unit="IN" Qty="1" Size="32.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCh050" />
	</Part>
	
	<Part PartID="8026007-0">
		<Operation WC="ASY010">
			<Material PartID="8033647" Unit="EA" Qty="1" />
			<Material PartID="8033646" Unit="EA" Qty="1" />
			<Material PartID="1402408" Unit="EA" Qty="4" />
			<Material PartID="1527301" Unit="EA" Qty="4" />
			<Material PartID="1577301" Unit="EA" Qty="4" />
			<Material PartID="3402008" Unit="EA" Qty="9" />
			<Material PartID="1032001" Unit="EA" Qty="9" />
			<Material PartID="1422006" Unit="EA" Qty="4" />
			<Material PartID="1577201" Unit="EA" Qty="4" />
			<Material PartID="1527201" Unit="EA" Qty="4" />
		</Operation>
	</Part>
	
	<Part PartID="8026007-1">
		<Operation WC="ASY010">
			<Material PartID="8025796" Unit="EA" Qty="1" />
			<Material PartID="8025791" Unit="EA" Qty="1" />
			<Material PartID="1402408" Unit="EA" Qty="4" />
			<Material PartID="1527301" Unit="EA" Qty="4" />
			<Material PartID="1577301" Unit="EA" Qty="4" />
			<Material PartID="3402008" Unit="EA" Qty="9" />
			<Material PartID="1032001" Unit="EA" Qty="9" />
			<Material PartID="1422006" Unit="EA" Qty="4" />
			<Material PartID="1577201" Unit="EA" Qty="4" />
			<Material PartID="1527201" Unit="EA" Qty="4" />
		</Operation>
	</Part>
	
	<Part PartID="8026007-3">
		<Operation WC="ASY010">
			<Material PartID="8026343" Unit="EA" Qty="1" />
			<Material PartID="8026342" Unit="EA" Qty="1" />
			<Material PartID="1402408" Unit="EA" Qty="4" />
			<Material PartID="1527301" Unit="EA" Qty="4" />
			<Material PartID="1577301" Unit="EA" Qty="4" />
			<Material PartID="3402008" Unit="EA" Qty="13" />
			<Material PartID="1032001" Unit="EA" Qty="13" />
			<Material PartID="1422006" Unit="EA" Qty="5" />
			<Material PartID="1577201" Unit="EA" Qty="5" />
			<Material PartID="1527201" Unit="EA" Qty="5" />
		</Operation>
	</Part>
	
	<Part PartID="8026007-4">
		<Operation WC="ASY010">
			<Material PartID="8027541" Unit="EA" Qty="1" />
			<Material PartID="8027540" Unit="EA" Qty="1" />
			<Material PartID="1402408" Unit="EA" Qty="4" />
			<Material PartID="1527301" Unit="EA" Qty="4" />
			<Material PartID="1577301" Unit="EA" Qty="4" />
			<Material PartID="3402008" Unit="EA" Qty="17" />
			<Material PartID="1032001" Unit="EA" Qty="17" />
			<Material PartID="1422006" Unit="EA" Qty="6" />
			<Material PartID="1577201" Unit="EA" Qty="6" />
			<Material PartID="1527201" Unit="EA" Qty="6" />
		</Operation>
	</Part>
	
	<Part PartID="8026007-5">
		<Operation WC="ASY010">
			<Material PartID="8026859" Unit="EA" Qty="1" />
			<Material PartID="8026858" Unit="EA" Qty="1" />
			<Material PartID="1402408" Unit="EA" Qty="4" />
			<Material PartID="1527301" Unit="EA" Qty="4" />
			<Material PartID="1577301" Unit="EA" Qty="4" />
			<Material PartID="3402008" Unit="EA" Qty="23" />
			<Material PartID="1032001" Unit="EA" Qty="23" />
			<Material PartID="1422006" Unit="EA" Qty="8" />
			<Material PartID="1577201" Unit="EA" Qty="8" />
			<Material PartID="1527201" Unit="EA" Qty="8" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/C27876-X_HD Prec Angle Adj.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M33H"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8027877">
		<Operation WC="FAB010">
			<Material PartID="9192200" Unit="IN" Qty="1" Size="0.500" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
		<Operation WC="EXT010">
			<Material PartID="8027877-A" Unit="EA" Qty="1" /> <!--8027877-A is new item to cover dial engraving costs-->
		</Operation>
	</Part>
	
	<Part PartID="8027881">
		<Operation WC="MCH010">
			<Material PartID="6332010" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8033972">
		<Operation WC="FAB010">
			<Material PartID="9190240-4" Unit="IN" Qty="1" Size="4.90625" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8033975">
		<Operation WC="FAB010">
			<Material PartID="6332009" Unit="EA" Qty="1" Size="0.250" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8033973">
		<Operation WC="FAB010">
			<Material PartID="9190241-4" Unit="IN" Qty="1" Size="4.875" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH050" />
		<Operation WC="EXT010">
			<Material PartID="9816001" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8033974-1">
		<Operation WC="FAB010">
			<Material PartID="9092050-1" Unit="IN" Qty="1" Size="6.09375" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH030" />
		<Operation WC="MCH060" />
	</Part>
	
	<Part PartID="8033974-2">
		<Operation WC="FAB010">
			<Material PartID="9092050-1" Unit="IN" Qty="1" Size="6.21875" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH030" />
		<Operation WC="MCH060" />
	</Part>

<!--	Defined in Model76E.xml
	<Part PartID="8033976">
		<Operation WC="MCH010">
			<Material PartID="6092022" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="MCH060" />
	</Part>
-->
	
	<Part PartID="8027876-X">
		<Operation WC="ASY010">
			<Material PartID="8027877" Unit="EA" Qty="1" />
			<Material PartID="8027881" Unit="EA" Qty="1" />
			<Material PartID="8033972" Unit="EA" Qty="1" />
			<Material PartID="8033975" Unit="EA" Qty="1" />
			<Material PartID="8033973" Unit="EA" Qty="1" />
			<!-- <Material PartID="8033369" Unit="EA" Qty="1" /> Defined on 8033334-X -->
			<Material PartID="8033976" Unit="EA" Qty="1" />
			<Material PartID="2331702" Unit="EA" Qty="1" />
			<Material PartID="1331404-1" Unit="EA" Qty="1" />
			<Material PartID="1421706" Unit="EA" Qty="4" />
			<Material PartID="1576101" Unit="EA" Qty="8" />
			<Material PartID="1506101" Unit="EA" Qty="8" />
			<Material PartID="1231703" Unit="EA" Qty="4" />
			<Material PartID="1402408" Unit="EA" Qty="3" />
			<Material PartID="1577301" Unit="EA" Qty="3" />
			<Material PartID="1527301" Unit="EA" Qty="4" />
			<Material PartID="1102801" Unit="EA" Qty="2" />
			<Material PartID="1527401" Unit="EA" Qty="1" />
			<Material PartID="1477606" Unit="EA" Qty="1" />
			<Material PartID="1527601" Unit="EA" Qty="1" />
			<Material PartID="3030023" Unit="EA" Qty="1" />
			<Material PartID="3032003" Unit="EA" Qty="1" />
			<Material PartID="6094007" Unit="EA" Qty="2" />
			<Material PartID="6230006" Unit="EA" Qty="2" />
			<Material PartID="6370006" Unit="EA" Qty="1" />
			<Material PartID="6370023" Unit="EA" Qty="1" />
			<Material PartID="6541003" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027876-1">
		<Operation WC="ASY010">
			<Material PartID="8027876-X" Unit="EA" Qty="1" />
			<Material PartID="8033974-1" Unit="EA" Qty="1" />
			<Material PartID="8033971-1" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027876-2">
		<Operation WC="ASY010">
			<Material PartID="8027876-X" Unit="EA" Qty="1" />
			<Material PartID="8033974-2" Unit="EA" Qty="1" />
			<Material PartID="8033971-2" Unit="EA" Qty="1" />
		</Operation>
	</Part>

</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/8027098.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="8027098"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">
	
	<Part PartID="8025042">
		<Operation WC="ASY010">
			<Material PartID="8025042-A" Unit="EA" Qty="1" />
		</Operation>	
		<Operation WC="EXT010">
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
		<Operation WC="ASY010">
			<Material PartID="3110004" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027099">
		<Operation WC="FAB010">
			<Material PartID="3703501" Unit="IN" Qty="1" Size="7.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="EXT010">
			<Material PartID="9816011" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
	<Part PartID="8027100">
		<Operation WC="FAB010">
			<Material PartID="9073051" Unit="IN" Qty="1" Size="2.5" />
		</Operation>
		<Operation WC="MCH010" />
		<Operation WC="MCH060" />
		<Operation WC="FAB070">
			<Material PartID="1507201" Unit="EA" Qty="1" />
		</Operation>	
	</Part>
	
	<Part PartID="8027098">
		<Operation WC="ASY010">
			<Material PartID="8027100" Unit="EA" Qty="1" />
			<Material PartID="8027099" Unit="EA" Qty="1" />
			<Material PartID="8025042" Unit="EA" Qty="1" />
			<Material PartID="6680003" Unit="EA" Qty="1" />
			<Material PartID="6741006" Unit="EA" Qty="1" />
			<Material PartID="6541004" Unit="EA" Qty="1" />
			<Material PartID="6230007" Unit="EA" Qty="1" />
			<Material PartID="2033501" Unit="EA" Qty="1" />
			<Material PartID="3031003" Unit="EA" Qty="1" />
			<Material PartID="2577401" Unit="EA" Qty="1" />
			<Material PartID="2402816" Unit="EA" Qty="1" />
		</Operation>
	</Part>
	
</Parts>

=== MilesStarr/TACTIC_ERP_Phase2BOM/M900.xml
<?xml version="1.0" encoding="utf-8"?>
<Parts Group="M900 Ball Transfers"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BOM.xsd">

	<Part PartID="M900"> <!-- clean -->
		<Operation WC="ASY010">
			<Material PartID="8028587" Unit="EA" Qty="1" /> <!-- clean -->
			<Material PartID="8028639" Unit="EA" Qty="1" /> <!-- purchased -->
			<Material PartID="6960015" Unit="EA" Qty="1" /> <!-- purchased -->
			<Material PartID="6960036" Unit="EA" Qty="230" /> <!-- purchased -->
		</Operation>
	</Part>

	<Part PartID="8028587"> <!-- clean -->
		<Operation WC="EXT010">
			<Material PartID="8028587-A" Unit="EA" Qty="1" /> <!-- purchased -->
			<Material PartID="8028587-B" Unit="EA" Qty="1" /> <!-- purchased -->
		</Operation>
	</Part>

</Parts>
